if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! 
endif

set nocompatible
syntax on
filetype plugin indent on
set visualbell
set showcmd
set relativenumber
set number
set hlsearch
set incsearch

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set nobackup
set nowritebackup
set noswapfile
set undodir=~/.vimundodir

let &t_SI.="\e[6 q" " SI = INSERT mode
let &t_SR.="\e[4 q" " SR = REPLACE mode
let &t_EI.="\e[2 q" " EI = NORMAL mode (ELSE)

call plug#begin()
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-commentary'
  " Plug 'tpope/vim-repeat'
  Plug 'vim-scripts/ReplaceWithRegister'
  Plug 'christoomey/vim-system-copy'
  Plug 'justinmk/vim-sneak'
  Plug 'machakann/vim-highlightedyank'
call plug#end()

nnoremap <silent> H :bprevious<CR>
nnoremap <silent> L :bnext<CR>
